# Generated by Django 3.2.7 on 2021-09-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210919_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='book_publisher',
        ),
    ]
