# Generated by Django 3.2.7 on 2021-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='no_visits',
            field=models.IntegerField(default=0),
        ),
    ]
