# Generated by Django 3.2.7 on 2021-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_sinhala',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='title_sinhala',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='booktype',
            name='title_sinhala',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='publisher',
            name='title_sinhala',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
