# Generated by Django 3.2.7 on 2021-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210918_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='tel',
        ),
        migrations.AddField(
            model_name='publisher',
            name='land_tel',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='tel1',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='tel2',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
    ]
