# Generated by Django 3.2.7 on 2021-09-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210920_0428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='BookAuthor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='book_author',
        ),
    ]
