# Generated by Django 3.2.7 on 2021-09-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
    ]
