# Generated by Django 3.2.7 on 2021-09-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0009_delete_bookauthor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='BookPublisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='book_publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
    ]
