# Generated by Django 3.2.7 on 2021-09-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_publisher',
        ),
        migrations.DeleteModel(
            name='BookPublisher',
        ),
    ]
