# Generated by Django 3.2.7 on 2021-09-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_tel', models.CharField(max_length=11)),
                ('sender_message', models.TextField(max_length=500)),
            ],
        ),
    ]
